### ISSUE TITLE
Enhance Continuous Testing and Monitoring in Glycolysis Simulation

### ISSUE THREAD

**Issue by csmangum** [Dooders/AgentCell#12]
# **Issue: Enhance Continuous Testing and Monitoring in Glycolysis Simulation**

**Issue ID:** [Assign an ID, e.g., `#123`]

---

## **Description**

The glycolysis simulation currently lacks robust continuous testing and monitoring mechanisms. This absence has led to inconsistencies and errors in the simulation results, as previously identified. To improve the reliability and accuracy of the simulation, we need to implement enhanced testing strategies that can detect errors or undesired behaviors during runtime.

---

## **Objectives**

- **Incorporate Continuous Testing:** Integrate testing mechanisms that operate during the simulation's execution to catch errors in real-time.
- **Improve Error Detection:** Identify inconsistencies, logical errors, and violations of conservation laws promptly.
- **Enhance Logging and Reporting:** Provide detailed logs and reports to facilitate debugging and understanding of the simulation's state.
- **Maintain Simulation Integrity:** Ensure that the simulation maintains mass balance, energy conservation, and other critical invariants.

---

### **1. Implement Assertions and Invariants**

**Description:**

- Use `assert` statements throughout the code to enforce that certain conditions must always be true.
- Include invariants after key operations to ensure the simulation state remains valid.

**Action Items:**

- Add assertions to check mass balance after each reaction.
- Assert that metabolite concentrations remain non-negative.
- Verify that total adenine nucleotide count remains constant unless intentionally altered.

**Example:**

```python
# Ensure adenine nucleotide balance is maintained
total_adenine_nucleotides = atp + adp + amp
assert total_adenine_nucleotides == initial_adenine_nucleotides, "Adenine nucleotide count mismatch!"

# Check that metabolite concentrations are non-negative
for metabolite, amount in metabolite_levels.items():
    assert amount >= 0, f"Negative concentration detected for {metabolite}"
```

---

### **2. Enhance Logging with Detailed Information**

**Description:**

- Use Python's `logging` module to record detailed information at various levels (`DEBUG`, `INFO`, `WARNING`, `ERROR`).
- Log key variables, state changes, and significant events to track the simulation's progress and identify anomalies.

**Action Items:**

- Configure the logging system to output logs to a file and/or console with timestamps.
- Include logging statements before and after reactions to record substrate and product levels.
- Log warnings when variables reach critical thresholds.

**Example:**

```python
import logging

# Configure logging
logging.basicConfig(level=logging.DEBUG, filename='simulation.log', filemode='w',
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger('glycolysis_simulation')

# In your simulation code
logger.debug(f"Step {step}: ATP = {atp}, ADP = {adp}, AMP = {amp}")
logger.info(f"Glucose processed: {glucose_processed}")
logger.warning(f"NAD+ levels low: {nad_plus}")
logger.error(f"Adenine nucleotide imbalance detected at step {step}")
```

---

### **3. Integrate Unit Tests within the Simulation**

**Description:**

- Write unit tests for individual functions and methods to ensure they behave as expected.
- Run these tests periodically during the simulation to catch regressions or unintended side effects.

**Action Items:**

- Develop unit tests for each reaction function, checking correct consumption and production of metabolites.
- Periodically execute test functions during the simulation, especially after complex reactions or cycles.

**Example:**

```python
def test_adenine_nucleotide_balance():
    assert atp + adp + amp == initial_adenine_nucleotides, "Adenine nucleotide imbalance"

# During simulation
if step % test_interval == 0:
    test_adenine_nucleotide_balance()
```

---

### **4. Implement Real-time Monitoring and Visualization**

**Description:**

- Use visualization libraries to create dynamic plots that update in real-time.
- Visualize critical parameters such as ATP levels, metabolite concentrations, and reaction rates.

**Action Items:**

- Integrate a plotting library like Matplotlib or Plotly.
- Create functions to update plots at each simulation step or at defined intervals.
- Visualize trends and detect anomalies through graphical representations.

**Example:**

```python
import matplotlib.pyplot as plt

# Initialize plots
fig, ax = plt.subplots()
line_atp, = ax.plot([], [], label='ATP')
line_adp, = ax.plot([], [], label='ADP')
ax.legend()

# Update function
def update_plot(step, atp_levels, adp_levels):
    line_atp.set_xdata(range(step))
    line_atp.set_ydata(atp_levels)
    line_adp.set_xdata(range(step))
    line_adp.set_ydata(adp_levels)
    ax.relim()
    ax.autoscale_view()
    plt.draw()
    plt.pause(0.01)

# During simulation
atp_levels.append(atp)
adp_levels.append(adp)
update_plot(step, atp_levels, adp_levels)
```

---

### **5. Set Thresholds and Alerts**

**Description:**

- Define acceptable ranges for critical variables.
- Trigger alerts or take corrective actions when variables exceed these thresholds.

**Action Items:**

- Establish threshold values for metabolites like ATP, NAD+, and pyruvate.
- Implement checks to compare current values against thresholds.
- Decide on actions to take when thresholds are crossed (e.g., logging a warning, halting the simulation).

**Example:**

```python
# Define thresholds
ATP_CRITICAL_LOW = 2.0
NAD_PLUS_CRITICAL_LOW = 1.0

# Check thresholds
if atp < ATP_CRITICAL_LOW:
    logger.warning(f"ATP levels critically low: {atp}")
    # Potentially adjust reaction rates or halt simulation

if nad_plus < NAD_PLUS_CRITICAL_LOW:
    logger.warning(f"NAD+ levels critically low: {nad_plus}")
```

---

### **6. Use Exception Handling with Custom Error Messages**

**Description:**

- Wrap critical code sections in try-except blocks to handle exceptions gracefully.
- Raise custom exceptions with informative messages when unexpected conditions occur.

**Action Items:**

- Identify sections of code where exceptions may occur (e.g., division by zero, negative concentrations).
- Implement custom exception classes if needed.
- Ensure that exceptions are logged with sufficient detail for debugging.

**Example:**

```python
class ReactionError(Exception):
    pass

try:
    # Perform a reaction
    execute_reaction('Hexokinase')
except ReactionError as e:
    logger.error(f"Reaction failed: {e}")
    # Handle the error appropriately
```

---

### **7. Periodic State Validation Functions**

**Description:**

- Create functions that validate the entire simulation state at regular intervals.
- Ensure that fundamental conservation laws (mass, energy) are not violated.

**Action Items:**

- Implement validation functions to check total mass, energy, and critical balances.
- Schedule these validations to run periodically during the simulation.
- Log the results of each validation, and handle any detected inconsistencies.

**Example:**

```python
def validate_simulation_state():
    # Check mass balance
    total_mass = sum(metabolite_levels.values())
    assert abs(total_mass - initial_total_mass) < TOLERANCE, "Mass balance violated"

    # Check conservation of energy, if applicable

# During simulation
if step % validation_interval == 0:
    validate_simulation_state()
```

---

### **8. Implement Checkpoints and Rollbacks**

**Description:**

- Save the simulation state at intervals to allow for rollback in case of errors.
- Prevent data loss and facilitate debugging by maintaining snapshots of the state.

**Action Items:**

- Decide on a checkpointing interval based on simulation length and available storage.
- Implement functions to save and load the simulation state.
- Handle errors by rolling back to the last good checkpoint when necessary.

**Example:**

```python
import pickle

def save_checkpoint(step):
    with open(f'checkpoint_step_{step}.pkl', 'wb') as f:
        pickle.dump({'metabolite_levels': metabolite_levels, 'step': step}, f)

def load_checkpoint(step):
    with open(f'checkpoint_step_{step}.pkl', 'rb') as f:
        checkpoint = pickle.load(f)
    return checkpoint['metabolite_levels'], checkpoint['step']

# During simulation
if step % checkpoint_interval == 0:
    save_checkpoint(step)

# On error
metabolite_levels, step = load_checkpoint(last_good_step)
```

---

### **9. Use Automated Testing Frameworks**

**Description:**

- Integrate testing frameworks like `pytest` or `unittest` for automated testing.
- Write test cases that cover different aspects of the simulation, including edge cases.

**Action Items:**

- Set up a testing environment using `pytest`.
- Write test functions for reactions, balance checks, and other critical components.
- Configure tests to run automatically before or during simulations.

**Example with pytest:**

```python
# test_simulation.py
def test_nad_balance():
    total_nad = metabolite_levels['NAD+'] + metabolite_levels['NADH']
    assert total_nad == initial_nad_total, "NAD+/NADH balance violated"

def test_atp_production():
    expected_atp = initial_atp + net_atp_produced
    assert metabolite_levels['ATP'] == expected_atp, "ATP production mismatch"
```

---

### **10. Code Profiling and Performance Monitoring**

**Description:**

- Use profiling tools to monitor performance and identify bottlenecks.
- Ensure that performance issues do not lead to errors under certain conditions.

**Action Items:**

- Utilize modules like `cProfile` for CPU profiling and `memory_profiler` for memory usage.
- Profile the simulation to identify slow or resource-intensive sections.
- Optimize code where necessary to improve performance.

**Example:**

```python
import cProfile

def run_simulation():
    # Simulation code

if __name__ == '__main__':
    cProfile.run('run_simulation()', filename='simulation_profile.stats')
```

---

## **Tasks**

1. **Add Assertions and Invariants**  
   - [x] #13
   - [x] Test assertions by intentionally introducing errors to ensure they trigger.

2. **Enhance Logging**  
   - [ ] Set up the logging configuration.
   - [ ] Add logging statements throughout the code.
   - [ ] Ensure logs provide sufficient detail for debugging.

3. **Integrate Unit Tests**  
   - [ ] Write unit tests for each reaction function.
   - [ ] Incorporate unit tests into the simulation loop.
   - [ ] Ensure tests cover both normal and edge cases.

4. **Implement Real-time Visualization**  
   - [ ] Choose a suitable plotting library.
   - [ ] Create initial plots for key variables.
   - [ ] Update plots during the simulation.

5. **Set Thresholds and Alerts**  
   - [ ] Define threshold values for critical variables.
   - [ ] Implement checks and alert mechanisms.
   - [ ] Decide on corrective actions when thresholds are exceeded.

6. **Use Exception Handling**  
   - [ ] Implement try-except blocks around critical code sections.
   - [ ] Define custom exception classes if needed.
   - [ ] Ensure exceptions are logged with detailed messages.

7. **Periodic State Validation**  
   - [ ] Write validation functions for mass balance, energy conservation, etc.
   - [ ] Schedule validations to run at defined intervals.
   - [ ] Handle detected inconsistencies appropriately.

8. **Implement Checkpoints and Rollbacks**  
   - [ ] Decide on checkpointing strategy.
   - [ ] Implement save and load functions for the simulation state.
   - [ ] Test rollback functionality by simulating errors.

9. **Use Automated Testing Frameworks**  
   - [ ] Set up `pytest` or another testing framework.
   - [ ] Write comprehensive test cases.
   - [ ] Integrate tests into development workflow.

10. **Profile and Optimize Code**  
    - [ ] Use profiling tools to analyze performance.
    - [ ] Identify and optimize bottlenecks.
    - [ ] Monitor resource usage during long simulations.

---

## **Additional Notes**

- **Documentation:** Update or create documentation for any new functions, classes, or modules added during this process.
- **Version Control:** Commit changes incrementally with descriptive commit messages to track progress.
- **Collaboration:** If working in a team, ensure that all members are aware of these changes and understand the new testing mechanisms.
- **Future Enhancements:** Consider integrating continuous integration (CI) tools to automate testing during code changes.

---

## **References**

- **Python `logging` Module:** [https://docs.python.org/3/library/logging.html](https://docs.python.org/3/library/logging.html)
- **pytest Documentation:** [https://docs.pytest.org/en/stable/](https://docs.pytest.org/en/stable/)
- **Matplotlib Tutorial:** [https://matplotlib.org/stable/tutorials/index.html](https://matplotlib.org/stable/tutorials/index.html)
- **Profiling in Python:** [https://docs.python.org/3/library/profile.html](https://docs.python.org/3/library/profile.html)

---

## **Acceptance Criteria**

- The simulation incorporates continuous testing mechanisms that detect errors during runtime.
- Critical invariants (mass balance, energy conservation, nucleotide counts) are enforced and validated.
- Logs provide detailed information useful for debugging.
- Real-time monitoring tools help visualize the simulation state.
- Errors and undesired behaviors are identified promptly, and corrective actions are defined.

---

**Please proceed with implementing these enhancements. Feel free to update this issue with progress, questions, or any obstacles encountered.**
