### ISSUE TITLE
Identify critical variables and add assertions accordingly.

### ISSUE THREAD

**Issue by csmangum** [Dooders/AgentCell#13]
# **Issue: Identify Critical Variables and Add Assertions in Simulation Code**

**Issue ID:** [Assign an ID, e.g., `#124`]

---

## **Description**

To improve the robustness and reliability of the glycolysis simulation, we need to identify critical variables and implement assertions that enforce invariants and validate assumptions throughout the code. This will help in catching errors early and ensuring that the simulation maintains consistency and correctness during execution.

---

## **Objectives**

- **Identify Critical Variables:**
  - Determine which variables are essential for the correct functioning of the simulation.
  - Focus on variables whose incorrect values could lead to significant errors or invalid simulation states.

- **Add Assertions:**
  - Implement `assert` statements to check that these critical variables meet expected conditions.
  - Ensure that the assertions are meaningful and provide clear error messages when conditions are not met.

---

## **Tasks**

1. **Review the Simulation Code:**
   - [x] #14
   - [x] List all critical variables that influence the simulation's integrity.

2. **Identify Critical Variables:**
   - [x] Variables related to mass balance (e.g., total mass of metabolites).
   - [x] Energy-related variables (e.g., ATP, ADP, AMP levels).
   - [x] Conservation of cofactors (e.g., NAD+, NADH).
   - [x] Metabolite concentrations that should remain non-negative.
   - [x] Reaction rates and parameters that should stay within biologically plausible ranges.

3. **Define Expected Conditions:**
   - [x] For each critical variable, define the conditions that must always hold true.
   - [x] Examples:
     - Total adenine nucleotide count should remain constant unless intentionally altered.
     - Metabolite concentrations should never be negative.
     - Ratios between certain metabolites should stay within expected ranges.

4. **Implement Assertions:**
   - [ ] Add `assert` statements in the code to enforce the expected conditions.
   - [ ] Ensure that assertions are placed at appropriate points in the code, such as after reactions or state updates.
   - [ ] Include informative error messages in assertions to facilitate debugging.

5. **Test Assertions:**
   - [ ] Intentionally introduce errors or edge cases to verify that assertions trigger as expected.
   - [ ] Adjust assertions if necessary to avoid false positives or negatives.

6. **Document the Assertions:**
   - [ ] Comment the code to explain why each assertion is important.
   - [ ] Update any relevant documentation to reflect the new assertions and their purposes.

---

## **Examples of Critical Assertions**

- **Adenine Nucleotide Balance:**

  ```python
  total_adenine_nucleotides = (
      metabolite_levels['ATP'] +
      metabolite_levels['ADP'] +
      metabolite_levels.get('AMP', 0.0)
  )
  assert total_adenine_nucleotides == initial_adenine_nucleotides, (
      f"Adenine nucleotide count mismatch! "
      f"Initial: {initial_adenine_nucleotides}, Current: {total_adenine_nucleotides}"
  )
  ```

- **Non-negative Metabolite Concentrations:**

  ```python
  for metabolite, amount in metabolite_levels.items():
      assert amount >= 0, f"Negative concentration detected for {metabolite}: {amount}"
  ```

- **NAD+/NADH Balance:**

  ```python
  total_nad = metabolite_levels['NAD+'] + metabolite_levels['NADH']
  assert total_nad == initial_nad_total, (
      f"NAD+/NADH balance mismatch! "
      f"Initial: {initial_nad_total}, Current: {total_nad}"
  )
  ```

- **Mass Conservation:**

  ```python
  current_total_mass = sum(metabolite_levels.values())
  assert abs(current_total_mass - initial_total_mass) < TOLERANCE, (
      f"Mass balance violated! "
      f"Initial: {initial_total_mass}, Current: {current_total_mass}"
  )
  ```

---

## **Acceptance Criteria**

- All critical variables in the simulation code are identified and documented.
- Assertions are added to enforce conditions that these variables must satisfy.
- Assertions are tested and verified to trigger appropriately when conditions are not met.
- The simulation code runs without assertion errors under normal conditions.
- Code is well-documented, with comments explaining the purpose of each assertion.

---

## **Additional Notes**

- **Performance Considerations:**
  - Be mindful that excessive use of assertions in performance-critical sections may impact simulation speed.
  - Consider disabling assertions in production runs if performance becomes an issue, but keep them enabled during development and testing.

- **Error Handling:**
  - Ensure that when an assertion fails, it provides enough context to diagnose the issue.
  - Consider using custom exception classes if more sophisticated error handling is required.

- **Collaboration:**
  - If working with a team, coordinate to ensure that everyone is aware of the critical variables and the added assertions.

---

## **Deadline**

- **Proposed Completion Date:** [Specify a realistic deadline based on project timelines]

---

## **References**

- **Python Assertions:** [https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)
- **Best Practices for Using Assertions:** [https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python](https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python)

---

**Please begin work on identifying critical variables and adding assertions accordingly. Update this issue with progress notes or any questions that arise.**
